# -*- coding: utf-8 -*-
"""Cópia de Olá, este é o Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_CnYYlYJGSm3f9BetusXDcgWMooLS7ce
"""

import pandas as pd

tabela_clientes = pd.read_csv("/clientes.csv")
display(tabela_clientes )

